language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-23.0.0
    - android-23
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'