language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-23.0.0
    - android-23
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  install:
      - echo yes | sdkmanager \"tools\"",
      - echo yes | sdkmanager \"platforms;android-23\"",
      - echo yes | sdkmanager \"extras;android;m2repository\"",
      - echo yes | sdkmanager \"extras;google;m2repository\"",
      - echo yes | sdkmanager \"extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2\"",
      - echo yes | sdkmanager \"extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2\"",
